In [27]:
import pandas as pd
import numpy as np
df=pd.read_csv("/Users/prateekb/Downloads/MyPrograms/Certification/WIP/Machine Learning/CrossValidationAndBoosting/mtcars_for_manymerge.csv")
df

                   Cars   mpg  cyl   disp   hp  drat  Feedback
0              MazdaRX4  21.0    6  160.0  110  3.90         1
1          MazdaRX4_WAG  21.0    6  160.0  110  3.90         0
2            Datsun_710  22.8    4  108.0   93  3.85         1
3        Hornet_4_Drive  21.4    6  258.0  110  3.08         1
4     Hornet_Sportabout  18.7    8  360.0  175  3.15         1
5               Valiant  18.1    6  225.0  105  2.76         1
6            Duster_360  14.3    8  360.0  245  3.21         0
7             Merc_240D  24.4    4  146.7   62  3.69         0
8              Merc_230  22.8    4  140.8   95  3.92         1
9              Merc_280  19.2    6  167.6  123  3.92         0
10            Merc_280C  17.8    6  167.6  123  3.92         0
11           Merc_450SE  16.4    8  275.8  180  3.07         0
12           Merc_450SL  17.3    8  275.8  180  3.07         1
13          Merc_450SLC  15.2    8  275.8  180  3.07         1
14   Cadillac_Fleetwood  10.4    8  472.0  205  2.93         1
15  Lincoln_Continental  10.4    8  460.0  215  3.00         0
16    Chrysler_Imperial  14.7    8  440.0  230  3.23         1
17             Fiat_128  32.4    4   78.7   66  4.08         1
18          Honda_Civic  30.4    4   75.7   52  4.93         0
19       Toyota_Corolla  33.9    4   71.1   65  4.22         0
20        Toyota_Corona  21.5    4  120.1   97  3.70         0

In [28]:
X=df[['cyl','hp']]
Y=df['Feedback']
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
knnc=KNeighborsClassifier(n_neighbors=4)
from sklearn.model_selection import cross_val_score
cross_val_score(knnc,X,Y,cv=10,scoring='accuracy').mean()

0.5666666666666667

In [29]:
from sklearn.linear_model import LogisticRegression
lr=LogisticRegression()
from sklearn.model_selection import cross_val_score
cross_val_score(lr,X,Y,cv=10,scoring='accuracy').mean()

0.3333333333333333

In [31]:
from sklearn.ensemble import AdaBoostClassifier
abc=AdaBoostClassifier()
cross_val_score(abc,X,Y,cv=10,scoring='accuracy').mean()

0.5166666666666666